### PR TITLE
Add support for faster_whisper_server

### PR DESCRIPTION
**Pull request by gsoul**
faster whisper server (https://github.com/fedirz/faster-whisper-server) has API identical to the OpenAI's API.  So the only thing that is needed to support it are the environment variables. To direct the OpenAI's library to the local url.

### CODE REVIEW

**Review by dhruvyad — COMMENTED** [review]
Thanks for adding this! Since you're changing the interfaces, could you please update README as well accordingly?

**Comment by gsoul** [comment]
Sure, I'll update it a bit later.

**Comment by gsoul** [comment]
@dhruvyad please kindly take another look.

**Review by dhruvyad — APPROVED** [review]
Thanks!

**Comment by gsoul** [comment]
@dhruvyad would you merge this PR?

**Pull request merged**
